### PR TITLE
Drop `laminas/laminas-zendframework-bridge` and `zendframework/*` compatibility

### PR DESCRIPTION
**Pull request by PowerKiKi**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Increase performance by removing a compatibility layer while **not** introducing breaking changes.

This follow the process described in details in:

https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2021-08-02-TSC-Minutes.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
CI failing due to missing `composer.lock` - see #24 review

**Comment by PowerKiKi** [comment]
See https://github.com/laminas/laminas-skeleton-installer/pull/26 for an attemps at restoring CI

**Comment by Ocramius** [comment]
@samsonasik if you can re-generate `composer.lock`, can we push that here?

**Comment by samsonasik** [comment]
@Ocramius oh, just realized composer.lock should be re-generated here.

**Comment by samsonasik** [comment]
@Ocramius I forced push for re-generated composer.lock here 🎉

**Comment by samsonasik** [comment]
@Ocramius All green 🎉

**Review by Ocramius — APPROVED** [review]
Thanks @PowerKiKi and @samsonasik!

**Pull request merged**
